# Generated by Django 4.0.4 on 2022-04-22 10:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carss', '0003_auto_20220422_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
