# Generated by Django 4.0.4 on 2022-04-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carss', '0005_alter_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_photo_1',
            new_name='car_photo',
        ),
    ]
